Repository STUDIO-EYE/STUDIO-EYE-WEB-PROMOTION, pull requests merged in 2024-10, with the labels that each got.

#139 [Feat/SCRUM-274] header 반응형
  build/asset-manifest.json
  build/index.html
  src/components/PromotionPage/CustomCursor/CustomCursor.tsx
  src/components/PromotionPage/Header/Header.tsx
  src/components/PromotionPage/Header/HeaderDetail.tsx
  src/components/PromotionPage/Header/Menubar.tsx
  src/components/PromotionPage/Header/NavBtn.tsx
Labels: feat

#146 [Feat/SCRUM-243-PP] Footer Responsive
  src/components/PromotionPage/Footer/Footer.tsx
Labels: feat

#147 [Fix/SCRUM-254-PP] Header Menubar 고정되지 않는 문제
  build/asset-manifest.json
  build/index.html
  src/components/PromotionPage/Footer/Footer.tsx
  src/components/PromotionPage/Header/Menubar.tsx
  src/components/PromotionPage/Layout/Layout.tsx
Labels: fix

#156 [Fix/ISSUE-PP] Footer Responsive 모바일 화면 수정
  src/components/PromotionPage/Footer/Footer.tsx
Labels: 🖼 디자인

#157 [fix] 이슈 해결
  src/apis/PromotionPage/artwork.ts
  src/components/Helmets/DetailHelments.tsx
  src/components/PromotionPage/Artwork/ArtworkCard.tsx
  src/components/PromotionPage/Artwork/Layout.tsx
  src/components/PromotionPage/Artwork/Navigation.tsx
  src/components/PromotionPage/Circle/Circle.tsx
  src/components/PromotionPage/Main/Intro.tsx
  src/components/PromotionPage/Main/Outro.tsx
  src/components/PromotionPage/Main/Top.tsx
  src/components/PromotionPage/WorkWithUs/WorkWithUs.tsx
  src/pages/PromotionPage/ArtworkPage/ArtworkPage.tsx
  src/pages/PromotionPage/Main/MainPage.tsx
Labels: 💥 버그

#165 [Feat/SCRUM-290-PP] Artwork Page e2e
  cypress/e2e/ArtworkPage.cy.ts
  cypress/fixtures/Artwork/artwork_data.json
  cypress/fixtures/Artwork/testImage.png
  cypress/fixtures/Artwork/testImage2.jpg
  cypress/support/hooks.ts
  cypress/support/types.d.ts
  src/components/Pagination/Pagination.tsx
  src/components/PromotionAdmin/Artwork/ArtworkCreating/ArtworkCreating.tsx
  src/components/PromotionAdmin/Artwork/ArtworkCreating/ArtworkDefaultValue.tsx
  src/components/PromotionAdmin/Artwork/CategoryDropDown.tsx
  src/components/PromotionPage/Login/Login.tsx
Labels: :recycle: 테스트

#168 [Feat/SCRUM-280] MainPage E2E Test Code
  cypress/cypress.config.ts
  cypress/e2e/MainPage.cy.ts
  cypress/fixtures/MainPage/artworkData.json
  cypress/fixtures/MainPage/defaultMainImg.jpg
  cypress/fixtures/MainPage/defaultTopImg.jpg
  cypress/fixtures/MainPage/introData.json
  cypress/screenshots/MainPage.cy.ts/MainPage E2E Test -- ArtworkList 데이터 O (failed).png
  cypress/support/types.d.ts
  src/apis/PromotionPage/faq.ts
  src/apis/PromotionPage/menu.ts
  src/components/PromotionPage/Main/ArtworkList.tsx
  src/components/PromotionPage/Main/Intro.tsx
  src/components/PromotionPage/Main/Outro.tsx
  src/components/PromotionPage/Main/Top.tsx
  src/pages/PromotionPage/FaqPage/FaqPage.tsx
  src/pages/PromotionPage/Main/MainPage.tsx
Labels: :recycle: 테스트

#169 [Feat/SCRUM-283-PP] about page e2e
  cypress/e2e/AboutPage.cy.ts
  src/pages/PromotionPage/AboutPage/AboutPage.tsx
  src/pages/PromotionPage/AboutPage/IntroPage.tsx
  src/pages/PromotionPage/AboutPage/WhatWeDoPage.tsx
Labels: :recycle: 테스트

#170 [Feat/SCRUM-282-PP] FAQ page e2e 수정
  cypress/e2e/faqPage.cy.ts
  src/pages/PromotionPage/FaqPage/FaqPage.tsx
Labels: :recycle: 테스트
