Repository STUDIO-EYE/STUDIO-EYE-WEB-PROMOTION, pull requests merged in 2024-11, with the labels that each got.

#177 Feat/161 artwork e2e
  cypress/e2e/ArtworkPage.cy.ts
  cypress/fixtures/Artwork/artwork_data.json
  cypress/fixtures/Artwork/testImage.png
  cypress/fixtures/Artwork/testImage2.jpg
  cypress/fixtures/Artwork/킹더랜드-detail1.png
  cypress/fixtures/Artwork/킹더랜드-detail2.png
  cypress/fixtures/Artwork/킹더랜드-main.png
  cypress/support/hooks.ts
  cypress/support/types.d.ts
  src/apis/PromotionAdmin/dataEdit.ts
  src/components/PromotionAdmin/Artwork/ArtworkCreating/ArtworkCreating.tsx
  src/components/PromotionAdmin/Artwork/ArtworkCreating/ArtworkDefaultValue.tsx
  src/components/PromotionAdmin/Artwork/ArtworkCreating/ImageUpload.tsx
  src/components/PromotionAdmin/Artwork/ArtworkDefault/Artwork.tsx
  src/components/PromotionAdmin/Artwork/ArtworkDefault/ArtworkBox.tsx
  src/components/PromotionAdmin/Artwork/ArtworkDefault/ArtworkDetail.tsx
  src/components/PromotionAdmin/Artwork/CategoryDropDown.tsx
  src/components/PromotionPage/Artwork/ArtworkCard.tsx
  src/components/PromotionPage/Artwork/NullException.tsx
  src/components/PromotionPage/Login/Login.tsx
  src/components/PromotionPage/SkeletonComponent/SkeletonComponent.tsx
  src/pages/PromotionAdmin/DataEditPage/PartnerPage/PartnerEditPage.tsx
  src/pages/PromotionPage/ArtworkPage/ArtworkPage.tsx
Labels: :recycle: 테스트

#180 [Feat/SCRUM-295-PP] main page e2e 코드 작성
  cypress/e2e/MainPage.cy.ts
  cypress/fixtures/MainPage/CJ_ENM_Logo.png
  cypress/fixtures/MainPage/Netflix_Logo.png
  cypress/fixtures/MainPage/PA_artwork_data.json
  cypress/fixtures/MainPage/PA_client_data.json
  cypress/fixtures/MainPage/PA_intro_data.json
  cypress/fixtures/MainPage/PP_artwork_data.json
  cypress/fixtures/MainPage/artworkData.json
  cypress/fixtures/MainPage/defaultMainImg.jpg
  cypress/fixtures/MainPage/defaultTopImg.jpg
  cypress/fixtures/MainPage/main1.jpg
  cypress/fixtures/MainPage/main2.png
  cypress/fixtures/MainPage/main3.png
  cypress/screenshots/MainPage.cy.ts/MainPage E2E Test -- ArtworkList 데이터 O (failed).png
  cypress/support/types.d.ts
  src/components/PromotionAdmin/Artwork/ArtworkCreating/ArtworkDefaultValue.tsx
  src/components/PromotionAdmin/Artwork/ArtworkDefault/ArtworkDetail.tsx
  src/components/PromotionAdmin/DataEdit/Client/Client.tsx
  src/components/PromotionAdmin/DataEdit/Company/EditForm/Introduction.tsx
  src/components/PromotionAdmin/DataEdit/Company/InputForm.tsx
  src/components/PromotionAdmin/DataEdit/Navigation/NavBtn.tsx
  src/components/PromotionAdmin/DataEdit/StyleComponents/Button.tsx
  src/components/PromotionAdmin/DataEdit/StyleComponents/LogoListItem.tsx
  src/components/PromotionPage/Header/Header.tsx
  src/components/PromotionPage/Main/ArtworkList.tsx
  src/components/PromotionPage/Main/Intro.tsx
  src/components/PromotionPage/Main/Outro.tsx
  src/components/PromotionPage/Main/Top.tsx
  src/components/TextEditor/TextColorEditor.tsx
  src/constants/introdutionConstants.ts
  src/pages/PromotionAdmin/DataEditPage/ClientPage/ClientEditPage.tsx
  src/pages/PromotionAdmin/DataEditPage/ClientPage/ClientWritePage.tsx
Labels: :recycle: 테스트

#181 [Feat/SCRUM-295-PP] main page e2e 코드 수정
  cypress/e2e/MainPage.cy.ts
Labels: :recycle: 테스트

#190 [Fix/SCRUM-250] AdminNews 작성 오류 수정
  src/pages/PromotionAdmin/NewsPage/NewsWritePage/NewsWritePage.tsx
  src/pages/PromotionAdmin/NewsPage/index.tsx
Labels: 💥 버그

#193 [Fix/SCRUM-265] main page 수정
  src/components/PromotionPage/Artwork/ArtworkCard.tsx
  src/components/PromotionPage/Client/ClientRowAnimation.tsx
  src/components/PromotionPage/Main/ArtworkList.tsx
  src/components/PromotionPage/Main/Intro.tsx
  src/components/PromotionPage/Main/Outro.tsx
  src/components/PromotionPage/WorkWithUs/WorkWithUs.tsx
  src/pages/PromotionPage/ArtworkPage/ArtworkDetailPage.tsx
  src/pages/PromotionPage/ArtworkPage/ArtworkPage.tsx
  src/pages/PromotionPage/Main/MainPage.tsx
Labels: 💥 버그

#195 [Test/SCRUM-298] about page e2e
  cypress/e2e/AboutPage.cy.ts
  cypress/e2e/AboutPage/Ceo.cy.ts
  cypress/e2e/AboutPage/Introduction.cy.ts
  cypress/e2e/AboutPage/Slogan.cy.ts
  cypress/e2e/AboutPage/WhatWeDo.cy.ts
  cypress/fixtures/AboutPage/CEOLogo.png
  cypress/fixtures/AboutPage/DetailData.json
  cypress/fixtures/AboutPage/IntroductionData.json
  cypress/fixtures/AboutPage/Slogan.png
  cypress/screenshots/AboutPage.cy.ts/E2E Test -- Mission rendering (failed).png
  cypress/screenshots/AboutPage.cy.ts/E2E Test -- Scroll Bar rendering (failed).png
  cypress/screenshots/AboutPage.cy.ts/E2E Test -- WhatWeDo section rendering with 1 to 5 items (failed).png
  cypress/screenshots/MainPage.cy.ts/MainPage E2E Test -- Intro (failed).png
  cypress/support/commands.ts
  cypress/support/hooks.ts
  package-lock.json
  package.json
  src/components/PromotionAdmin/DataEdit/Company/EditForm/Detail.tsx
  src/components/PromotionAdmin/DataEdit/Company/EditForm/Introduction.tsx
  src/components/PromotionAdmin/DataEdit/Company/InfoCard/Introduction.tsx
  src/components/PromotionAdmin/DataEdit/Company/InputForm.tsx
  src/components/PromotionAdmin/DataEdit/StyleComponents/Button.tsx
  src/constants/dataCyAttributes.ts
  src/pages/PromotionAdmin/DataEditPage/CEOPage/CEOEditPage.tsx
  src/pages/PromotionAdmin/DataEditPage/index.tsx
  src/pages/PromotionPage/AboutPage/AboutPage.tsx
Labels: :recycle: 테스트

#199 [Test/SCRUM-290] Artwork page e2e
  cypress/e2e/ArtworkPage.cy.ts
  cypress/fixtures/Artwork/artwork_data.json
  cypress/fixtures/Artwork/너결싫-detail1.png
  cypress/fixtures/Artwork/너결싫-main.jpeg
  cypress/fixtures/Artwork/킹더랜드-main responsive.png
  src/components/PromotionAdmin/Artwork/ArtworkCreating/ArtworkCreating.tsx
  src/components/PromotionAdmin/Artwork/ArtworkCreating/ArtworkDefaultValue.tsx
  src/components/PromotionAdmin/Artwork/ArtworkCreating/ImageUpload.tsx
  src/components/PromotionAdmin/Artwork/ArtworkDefault/ArtworkDetail.tsx
  src/pages/PromotionPage/ArtworkPage/ArtworkDetailPage.tsx
  src/types/PromotionAdmin/artwork.ts
  src/types/PromotionPage/artwork.ts
Labels: :recycle: 테스트

#205 [Test/SCRUM-316] PP Artwork 통합테스트
  cypress/e2e/Integration/ArtworkPage.cy.ts
  cypress/e2e/Integration/ArtworkPage.ts
  cypress/e2e/System/ArtworkPage.cy.ts
  src/components/PromotionAdmin/Artwork/ArtworkSequence/ArtworkSequence.tsx
  src/components/PromotionPage/Artwork/ArtworkCard.tsx
  src/components/PromotionPage/Artwork/Navigation.tsx
  src/components/PromotionPage/ArtworkDetail/RotatedCircle.tsx
  src/components/PromotionPage/ArtworkDetail/ScrollAnimatedComponent.tsx
  src/pages/PromotionAdmin/ArtworkPage/ArtworkDetail.tsx
  src/pages/PromotionPage/ArtworkPage/ArtworkDetailPage.tsx
  src/pages/PromotionPage/ArtworkPage/ArtworkPage.tsx
Labels: :recycle: 테스트

#204 [Test/SCRUM-314] Faq page Integration test
  cypress.config.ts
  cypress/e2e/Integration/FaqPage.cy.ts
  src/pages/PromotionPage/FaqPage/FaqPage.tsx
Labels: :recycle: 테스트

#208 [Test/SCRUM-312] PP MainPage 통합테스트
  cypress/e2e/Integration/MainPage.cy.ts
  cypress/fixtures/MainPage/디피-detail1.png
  cypress/fixtures/MainPage/디피-detail2.png
  cypress/fixtures/MainPage/디피-main.jpg
  cypress/fixtures/MainPage/스테이지업-detail.png
  cypress/fixtures/MainPage/스테이지업-main.jpg
  cypress/support/commands.ts
  src/components/Pagination/NewsPagination.tsx
  src/components/PromotionAdmin/DataEdit/Client/Client.tsx
  src/components/PromotionAdmin/DataEdit/StyleComponents/LogoListItem.tsx
  src/components/PromotionPage/Client/ClientRowAnimation.tsx
  src/components/PromotionPage/Main/Outro.tsx
  src/components/PromotionPage/Main/Top.tsx
  src/pages/PromotionPage/Main/MainPage.tsx
Labels: :recycle: 테스트

#210 [Test/SCRUM-313] Login Page Integration test
  cypress/e2e/Integration/LoginPage.cy.ts
  src/components/PromotionPage/Login/Login.tsx
Labels: :recycle: 테스트

#211 hotfix: 로그인 이메일 유효성 검사 해제
  src/components/PromotionPage/Login/Login.tsx
Labels: 💥 버그

#216 Chore: gateway 주소 삭제 및 기본 주소 통합, 로그인 이메일 유효성 검사 추가
  cypress/support/hooks.ts
  package.json
  src/apis/PromotionAdmin/login.ts
  src/components/PromotionPage/Login/Login.tsx
  src/constants/basicPathConstants.ts
Labels: :building_construction: 빌드

#219 [Refactor/SCRUM-319] Artwork Lighthouse 점수 개선
  cypress/e2e/Integration/ArtworkPage.cy.ts
  cypress/e2e/System/ArtworkPage.cy.ts
  src/Router.tsx
  src/components/PromotionPage/Artwork/ArtworkCard.tsx
  src/components/PromotionPage/Artwork/Navigation.tsx
  src/components/PromotionPage/Artwork/NullException.tsx
  src/components/PromotionPage/ArtworkDetail/ImageSlider.tsx
  src/components/PromotionPage/Layout/Loading.tsx
  src/constants/routerConstants.ts
  src/pages/PromotionPage/ArtworkPage/ArtworkDetailPage.tsx
  src/pages/PromotionPage/ArtworkPage/ArtworkPage.tsx
Labels: 🛠 리팩토링

#222 [Refactor/SCRUM-318] About Page Performance 개선
  package.json
  src/Router.tsx
  src/components/Loading/Loading.tsx
  src/components/PromotionPage/Layout/Loading.tsx
  src/loaders/aboutPageLoader.ts
  src/pages/ErrorPage/ErrorPage.tsx
  src/pages/PromotionPage/AboutPage/AboutPage.tsx
  src/pages/PromotionPage/AboutPage/IntroPage.tsx
  src/pages/PromotionPage/AboutPage/WhatWeDoPage.tsx
  src/types/PromotionPage/about.ts
  src/utils/withSuspense.tsx
Labels: 🛠 리팩토링

#223 [Refactor/SCRUM-321] News page Performance 개선
  src/components/PromotionPage/Artwork/NullException.tsx
  src/pages/PromotionPage/ArtworkPage/ArtworkPage.tsx
  src/pages/PromotionPage/NewsPage/IntroSection.tsx
  src/pages/PromotionPage/NewsPage/NewsBoardPage.tsx
  src/pages/PromotionPage/NewsPage/NewsSection.tsx
Labels: 🛠 리팩토링
