Repository STUDIO-EYE/STUDIO-EYE-WEB-PROMOTION, pull requests merged in 2024-12, with the labels that each got.

#212 [Test/SCRUM-312] Main Page Integration test - Add Exception Code
  cypress/e2e/Integration/MainPage.cy.ts
  src/apis/PromotionPage/artwork.ts
  src/components/PromotionAdmin/DataEdit/Company/InfoCard/Introduction.tsx
  src/components/PromotionPage/Main/ArtworkList.tsx
  src/components/PromotionPage/Main/ArtworkSlider.tsx
  src/components/PromotionPage/Main/Intro.tsx
  src/components/PromotionPage/Main/Outro.tsx
  src/pages/PromotionPage/Main/MainPage.tsx
Labels: :recycle: 테스트

#227 [Feat/SCRUM-331] Loading 컴포넌트 추가
  cypress/e2e/Integration/ArtworkPage.cy.ts
  src/apis/PromotionPage/artwork.ts
  src/components/Loading/Loading.tsx
  src/components/PromotionAdmin/Artwork/ArtworkHeader.tsx
  src/components/PromotionAdmin/Artwork/ArtworkSequence/ArtworkSequence.tsx
  src/components/PromotionPage/Artwork/NullException.tsx
  src/pages/PromotionAdmin/ArtworkPage/Artwork.tsx
  src/pages/PromotionPage/ArtworkPage/ArtworkPage.tsx
Labels: 🖼 디자인

#237 [Fix/SCRUM-#161] 아트워크 이슈 해결 및 test 일부 수정
  src/components/PromotionAdmin/Artwork/ArtworkCreating/ArtworkDefaultValue.tsx
  src/components/PromotionAdmin/Artwork/ArtworkCreating/ImageUpload.tsx
  src/components/PromotionAdmin/Artwork/ArtworkDefault/Artwork.tsx
  src/components/PromotionAdmin/Artwork/ArtworkDefault/ArtworkBox.tsx
  src/components/PromotionAdmin/Artwork/ArtworkDefault/ArtworkDetail.tsx
  src/components/PromotionAdmin/Artwork/ArtworkHeader.tsx
  src/components/PromotionAdmin/Artwork/ArtworkSequence/ArtworkSequence.tsx
  src/components/PromotionAdmin/Artwork/ArtworkSequence/ArtworkSequenceBox.tsx
  src/components/PromotionAdmin/Artwork/CategoryDropDown.tsx
  src/pages/PromotionPage/ArtworkPage/ArtworkPage.tsx
  src/pages/PromotionPage/Main/MainPage.tsx
Labels: 💥 버그, :recycle: 테스트, 🛠 리팩토링

#236 [Fix] PA Request Page, PP News Page, PA Menu Edit 이슈 해결
  src/apis/PromotionAdmin/menu.ts
  src/apis/PromotionAdmin/request.ts
  src/components/PromotionPage/Header/HeaderDetail.tsx
  src/pages/PromotionAdmin/DataEditPage/MenuPage/MenuPage.tsx
  src/pages/PromotionAdmin/RequestPage/RequestCheckPage.tsx
  src/pages/PromotionAdmin/RequestPage/RequestManagePage.tsx
  src/pages/PromotionPage/NewsPage/NewsBoardPage.tsx
  src/pages/PromotionPage/NewsPage/NewsSection.tsx
Labels: 💥 버그, 🛠 리팩토링

#239 [Fix] PA FAQ 관리 페이지, 리퀘스트 관리 페이지, 메뉴 페이지 이슈 처리
  src/pages/PromotionAdmin/DataEditPage/MenuPage/MenuPage.tsx
  src/pages/PromotionAdmin/FaqPage/FAQManagePage.tsx
  src/pages/PromotionAdmin/RequestPage/RequestCheckPage.tsx
  src/pages/PromotionAdmin/RequestPage/RequestManagePage.tsx
Labels: 💥 버그, 🖼 디자인

#240 [Refactor/SCRUM-339] PA Artwork 관리 페이지 이슈 해결
  src/components/PromotionAdmin/Artwork/ArtworkCreating/ArtworkCreating.tsx
  src/components/PromotionAdmin/Artwork/ArtworkCreating/ArtworkDefaultValue.tsx
  src/components/PromotionAdmin/Artwork/ArtworkCreating/ArtworkValueLayout.tsx
  src/components/PromotionAdmin/Artwork/ArtworkCreating/ImageUpload.tsx
  src/components/PromotionAdmin/Artwork/ArtworkDefault/Artwork.tsx
  src/components/PromotionAdmin/Artwork/ArtworkDefault/ArtworkBox.tsx
  src/components/PromotionAdmin/Artwork/ArtworkDefault/ArtworkDetail.tsx
  src/components/PromotionAdmin/Artwork/ArtworkDefault/ArtworkImgView.tsx
  src/components/PromotionAdmin/Artwork/ArtworkDefault/ArtworkInput.tsx
  src/components/PromotionAdmin/Artwork/ArtworkHeader.tsx
  src/components/PromotionAdmin/Artwork/CategoryDropDown.tsx
  src/components/PromotionAdmin/Header/index.tsx
  src/types/PromotionAdmin/artwork.ts
  src/utils/urlToFile.ts
Labels: 💥 버그, 🛠 리팩토링, 🖼 디자인

#241 [Fix] PA Recruitment 관리 페이지, PP FAQ 페이지, Recruitment 페이지 이슈 처리
  src/components/PromotionAdmin/Recruitment/index.tsx
  src/pages/PromotionAdmin/FaqPage/FAQManagePage.tsx
  src/pages/PromotionAdmin/RecruitmentPage/BenefitManagePage.tsx
  src/pages/PromotionAdmin/RecruitmentPage/BenefitWritePage.tsx
  src/pages/PromotionAdmin/RecruitmentPage/RecruitmentManagePage.tsx
  src/pages/PromotionAdmin/RecruitmentPage/RecruitmentWritePage.tsx
  src/pages/PromotionPage/FaqPage/FaqPage.tsx
  src/pages/PromotionPage/RecruitmentPage/RecruitmentPage.tsx
Labels: 💥 버그, 🛠 리팩토링, 🖼 디자인

#243 [Fix/Refactor] Issue Handling
  cypress/e2e/Integration/MainPage.cy.ts
  cypress/e2e/System/MainPage.cy.ts
  cypress/fixtures/Artwork/artwork_data.json
  src/components/PromotionPage/Main/ArtworkList.tsx
  src/components/PromotionPage/Main/ArtworkSlider.tsx
  src/components/PromotionPage/Main/Intro.tsx
  src/constants/messages.ts
  src/pages/PromotionAdmin/DataEditPage/MenuPage/MenuPage.tsx
  src/pages/PromotionAdmin/FaqPage/FAQCheckPage.tsx
  src/pages/PromotionAdmin/FaqPage/FAQManagePage.tsx
  src/pages/PromotionAdmin/RequestPage/RequestCheckPage.tsx
  src/pages/PromotionAdmin/RequestPage/RequestManagePage.tsx
  src/pages/PromotionPage/AboutPage/IntroPage.tsx
  src/pages/PromotionPage/Main/MainPage.tsx
Labels: 💥 버그, :recycle: 테스트, 🛠 리팩토링

#244 [Feat/SCRUM-340] 에러 컴포넌트 추가, 이슈 수정
  cypress/e2e/Integration/ArtworkPage.cy.ts
  cypress/e2e/System/ArtworkPage.cy.ts
  cypress/support/types.d.ts
  src/components/Error/ErrorComponent.tsx
  src/components/PromotionPage/Artwork/NullException.tsx
  src/components/PromotionPage/ArtworkDetail/ScrollAnimatedComponent.tsx
  src/components/PromotionPage/Header/HeaderDetail.tsx
  src/constants/ppErrorMessage.ts
  src/loaders/aboutPageLoader.ts
  src/pages/PromotionPage/AboutPage/AboutPage.tsx
  src/pages/PromotionPage/ArtworkPage/ArtworkPage.tsx
  src/pages/PromotionPage/ContactPage/ContactUsPage.tsx
  src/pages/PromotionPage/FaqPage/FaqPage.tsx
  src/pages/PromotionPage/Main/MainPage.tsx
  src/pages/PromotionPage/NewsPage/NewsBoardPage.tsx
  src/pages/PromotionPage/RecruitmentPage/RecruitmentPage.tsx
  src/types/PromotionPage/about.ts
Labels: 💥 버그, 🚀 기능, :recycle: 테스트

#245 [Test/SCRUM-174] about page partner e2e test 및 이슈 해결
  cypress/e2e/Integration/LoginPage.cy.ts
  cypress/e2e/System/AboutPage/Introduction.cy.ts
  cypress/e2e/System/AboutPage/Slogan.cy.ts
  cypress/e2e/System/AboutPage/WhatWeDo.cy.ts
  cypress/support/hooks.ts
  src/components/PromotionAdmin/Home/Graph/Graph.tsx
  src/components/PromotionAdmin/Home/Graph/LineGraph.tsx
  src/components/PromotionAdmin/Home/RequestSummary/RequestSummary.tsx
  src/components/PromotionAdmin/Home/RequestSummary/WaitingRequestsList.tsx
  src/hooks/useGraphData.tsx
Labels: 💥 버그, :recycle: 테스트

#246 hotfix: Main Page-Intro 섹션 오류 수정
  src/components/PromotionPage/Main/Intro.tsx
Labels: 💥 버그

#247 [Test/SCRUM-161] Artwork test 수정
  cypress/e2e/System/ArtworkPage.cy.ts
  src/components/PromotionAdmin/Artwork/ArtworkDefault/Artwork.tsx
Labels: 💥 버그, :recycle: 테스트

#248 hotfix: PP News Page 페이지네이션 스크롤 이슈 해결
  src/components/Pagination/NewsPagination.tsx
  src/components/PromotionAdmin/News/NewsList.tsx
  src/pages/PromotionAdmin/NewsPage/NewsViewPage/NewsEditPage.tsx
  src/pages/PromotionAdmin/NewsPage/NewsViewPage/NewsViewPage.tsx
  src/pages/PromotionAdmin/NewsPage/index.tsx
  src/pages/PromotionPage/NewsPage/NewsBoardPage.tsx
  src/pages/PromotionPage/NewsPage/NewsSection.tsx
Labels: 💥 버그, 🛠 리팩토링, 🖼 디자인

#251 hotfix: PP artwork detail 수정
  src/components/PromotionAdmin/Artwork/ArtworkSequence/ArtworkSequence.tsx
  src/components/PromotionPage/ArtworkDetail/ImageSlider.tsx
  src/pages/PromotionPage/ArtworkPage/ArtworkDetailPage.tsx
Labels: 💥 버그
